package com.example.solr.demo.dto;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

/**
 * Represents a single search result item combining:
 * 1. Solr Document Fields (id, sku, title_en, title_ar, short_description_en, short_description_ar)
 * 2. Relevance Score & Highlight Snippets generated by Solr's Highlighter
 * 3. Enriched Database details (Price, Stock, Brand, Category, Image) fetched from H2
 */
public class SearchResultItemDto {

    // --- Solr Core Fields ---
    private String id;
    private String sku;
    private String titleEn;
    private String titleAr;
    private String shortDescriptionEn;
    private String shortDescriptionAr;

    // --- Solr Search Metadata ---
    private Float score;
    private Map<String, List<String>> highlights;
    private String highlightedTitle;
    private String highlightedDescription;

    // --- Enriched Database Fields (from Relational Store) ---
    private BigDecimal price;
    private String currency;
    private String brand;
    private String categoryEn;
    private String categoryAr;
    private Boolean inStock;
    private Integer stockQuantity;
    private Double rating;
    private Integer reviewsCount;
    private String imageUrl;

    public SearchResultItemDto() {
    }

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getTitleEn() {
        return titleEn;
    }

    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn;
    }

    public String getTitleAr() {
        return titleAr;
    }

    public void setTitleAr(String titleAr) {
        this.titleAr = titleAr;
    }

    public String getShortDescriptionEn() {
        return shortDescriptionEn;
    }

    public void setShortDescriptionEn(String shortDescriptionEn) {
        this.shortDescriptionEn = shortDescriptionEn;
    }

    public String getShortDescriptionAr() {
        return shortDescriptionAr;
    }

    public void setShortDescriptionAr(String shortDescriptionAr) {
        this.shortDescriptionAr = shortDescriptionAr;
    }

    public Float getScore() {
        return score;
    }

    public void setScore(Float score) {
        this.score = score;
    }

    public Map<String, List<String>> getHighlights() {
        return highlights;
    }

    public void setHighlights(Map<String, List<String>> highlights) {
        this.highlights = highlights;
    }

    public String getHighlightedTitle() {
        return highlightedTitle;
    }

    public void setHighlightedTitle(String highlightedTitle) {
        this.highlightedTitle = highlightedTitle;
    }

    public String getHighlightedDescription() {
        return highlightedDescription;
    }

    public void setHighlightedDescription(String highlightedDescription) {
        this.highlightedDescription = highlightedDescription;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getCategoryEn() {
        return categoryEn;
    }

    public void setCategoryEn(String categoryEn) {
        this.categoryEn = categoryEn;
    }

    public String getCategoryAr() {
        return categoryAr;
    }

    public void setCategoryAr(String categoryAr) {
        this.categoryAr = categoryAr;
    }

    public Boolean getInStock() {
        return inStock;
    }

    public void setInStock(Boolean inStock) {
        this.inStock = inStock;
    }

    public Integer getStockQuantity() {
        return stockQuantity;
    }

    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public Integer getReviewsCount() {
        return reviewsCount;
    }

    public void setReviewsCount(Integer reviewsCount) {
        this.reviewsCount = reviewsCount;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}
